# setup
setup: scan
to_noisy_dataset: False # does not use labels

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: PRN18
pretext_path: r=0.4_sym_800ep_bs1024_PRN18

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Dataset
data_path: '../../datasets/red_blue/mini-imagenet/'
train_db_name: mini_imagenet32_red
val_db_name: mini_imagenet32_red
num_classes: 100
num_neighbors: 20

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   crop_size: 32

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 256
num_workers: 8

# Scheduler
scheduler: constant

